### ISSUE TITLE
IRIG.cpp:77:29: error return

### ISSUE THREAD

**Issue by MLouisss** [abc123me/arduino_irig#1]
Hi, thank you for your work,
I encounter error messages (for IRIG.cpp) when i try to run the library on an ESP32.

-----------------
sketch\IRIG.cpp: In member function 'uint8_t IRIG_RX::recv(irig_time_t*, uint32_t, uint8_t (*)())':
IRIG.cpp:77:29: error: return-statement with no value, in function returning 'uint8_t' {aka 'unsigned char'} [-fpermissive]
   if(started && pulse == 3) return;
                             ^~~~~~
exit status 1
return-statement with no value, in function returning 'uint8_t' {aka 'unsigned char'} [-fpermissive]
-----------------

I don't know if it's because of the ESP32 or the library itself.
Thank you for your help
LS

**Comment by abc123me** [comment]
Should be fixed, download & compile again. The ESP32 is not officially supported but should work fine. For now I will leave this open and if it compiles successfully please close the issue.

**Comment by MLouisss** [comment]
Thanks for your quick answer,
I've find a way to solve my problem with the ESP32 : As I use only the TX function, i have deleted the RX part in the library.

**Comment by abc123me** [comment]
Well good enough, I'm gonna call it fixed!
